export const actionList = {
    CREATE_TASK: 'CREATE_TASK',
    CHECK_TASK:  'CHECK_TASK',
    UNCHECK_TASK: 'UNCHECK_TASK',
    MAKE_TASK_PUBLIC: 'MAKE_TASK_PUBLIC',
    MAKE_TASK_PRIVATE: 'MAKE_TASK_PRIVATE',
    DELETE_TASK: 'DELETE_TASK',
};